[[prompts]]
id = "baseline.process_player_input"
csi = "csi/baseline-process-player-input.md.j2"
rc = "rc/baseline-process-player-input.md.j2"
fti = "fti/baseline-process-player-input.md.j2"

[[prompts]]
id = "plan.process_story_plan"
csi = "csi/plan-process-story-plan.md.j2"
rc = "rc/plan-process-story-plan.md.j2"
fti = "fti/plan-process-story-plan.md.j2"

[[prompts]]
id = "generate.generate_story"
csi = "csi/generate-generate-story.md.j2"
rc = "rc/generate-generate-story.md.j2"
fti = "fti/generate-generate-story.md.j2"

[[prompts]]
id = "summary.summarize_story"
csi = "csi/summary-summarize-story.md.j2"
rc = "rc/summary-summarize-story.md.j2"
fti = "fti/summary-summarize-story.md.j2"
